=== Bartosz-Banachowski/PKCK/Zadanie 1/zadanie1.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT dokument (autorzy,sklep_rowerowy)>

<!ELEMENT autorzy (autor)+>

<!ELEMENT autor (imię,nazwisko)>
<!ATTLIST autor
  Indeks CDATA #REQUIRED>

<!ELEMENT imię (#PCDATA)>

<!ELEMENT nazwisko (#PCDATA)>

<!ELEMENT sklep_rowerowy (rodzaj+,producenci)>
<!--powinno <!ELEMENT rodzaj (opis,lista_rowerów)> byc ale nie dziala  -->
<!ELEMENT rodzaj ANY>
<!ATTLIST rodzaj
  Id ID #REQUIRED>

<!ELEMENT opis (#PCDATA)>

<!ELEMENT lista_rowerów (rower)+>

<!ELEMENT producenci (p)+>

<!ELEMENT rower (producent,nazwa,waga,cena)>
<!ATTLIST rower
  Id ID #REQUIRED>

<!ELEMENT producent EMPTY>
<!ATTLIST producent
  idref IDREF #REQUIRED>

<!ELEMENT nazwa (#PCDATA)>

<!ELEMENT waga (#PCDATA)>
<!ATTLIST waga
  jednostka NMTOKEN #REQUIRED>

<!ELEMENT cena (#PCDATA)>
<!ATTLIST cena
  waluta NMTOKEN #REQUIRED>


<!ELEMENT p EMPTY>
<!ATTLIST p
  Id ID #REQUIRED
  kraj NMTOKEN #REQUIRED>

=== Bartosz-Banachowski/PKCK/Zadanie 1/Zadanie1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./zadanie1.css" type="text/css"?>
<!DOCTYPE dokument SYSTEM "zadanie1.dtd" >
<dokument>
    <autorzy>
        <autor Indeks="203979">
            <imię>Łukasz</imię>
            <nazwisko>Rogoziński</nazwisko>
        </autor>
        <autor Indeks="203849">
            <imię>Bartosz</imię>
            <nazwisko>Banachowski</nazwisko>
        </autor>
    </autorzy>
    <sklep_rowerowy>
        <rodzaj Id="S">Szosowy
            <opis>Typ rowerów przeznaczony do szybkiej jazdy po asfaltowej nawierzchni</opis> 
            <lista_rowerów>
                <rower Id="S01">
                    <producent idref="Kross" />
                    <nazwa>Kross Vento 2.0</nazwa>
                    <waga jednostka="kg">9,8</waga>
                    <cena waluta="zł">2599</cena>
                </rower>
                <rower Id="S02">
                    <producent idref="Specialized"/>
                    <nazwa>Allez Elite</nazwa>
                    <waga jednostka="kg">9,2</waga>
                    <cena waluta="zł">5799</cena>
                </rower>
                <rower Id="S03">
                    <producent idref="Trek" />
                    <nazwa>Domane SL 6 Disc</nazwa>
                    <waga jednostka="kg">8,8</waga>
                    <cena waluta="zł">15499</cena>
                </rower>
                <rower Id="S04">
                    <producent idref="Kross" />
                    <nazwa>Vento Te</nazwa>
                    <waga jednostka="kg">7,1</waga>
                    <cena waluta="zł">19999</cena>
                </rower>
                  <rower Id="S05">
                    <producent idref="Trek" />
                    <nazwa>Madone 9.5</nazwa>
                    <waga jednostka="kg">8,0</waga>
                    <cena waluta="zł">36999</cena>
                </rower>
            </lista_rowerów>
        </rodzaj>
        <rodzaj Id="G">Górskie
            <opis>Typ rowerów przeznaczony do jazdy po cięzkim terenie</opis>
            <lista_rowerów>
                <rower Id="G01">
                    <producent idref="Kross" />
                    <nazwa>Level 14.0</nazwa>
                    <waga jednostka="kg">9,7</waga>
                    <cena waluta="zł">15999</cena>
                </rower>
                <rower Id="G02">
                    <producent idref="Specialized" />
                    <nazwa>S-Works Epic XTR Di2</nazwa>
                    <waga jednostka="kg">8,3</waga>
                    <cena waluta="zł">44999</cena>
                </rower>
                <rower Id="G03">
                    <producent idref="Trek" />
                    <nazwa>Procaliber 9.7</nazwa>
                    <waga jednostka="kg">10,1</waga>
                    <cena waluta="zł">11299</cena>
                </rower>
                <rower Id="G04">
                    <producent idref="Kross" />
                    <nazwa>Roscoe 8</nazwa>
                    <waga jednostka="kg">8,8</waga>
                    <cena waluta="zł">4899</cena>
                </rower>
                <rower Id="G05">
                    <producent idref="Kross" />
                    <nazwa>Lea 4.0</nazwa>
                    <waga jednostka="kg">9,8</waga>
                    <cena waluta="zł">1699</cena>
                </rower>
            </lista_rowerów>
        </rodzaj>
         <rodzaj Id="M">Miejskie
            <opis>Typ rowerów przeznaczony do jazdy po mieście</opis>
            <lista_rowerów>
                <rower Id="M01">
                    <producent idref="Trek" />
                    <nazwa>T80 24 Speed Lowstep</nazwa>
                    <waga jednostka="kg">10,2</waga>
                    <cena waluta="zł">3199</cena>
                </rower>
                <rower Id="M02">
                    <producent idref="Le_Grand" />
                    <nazwa>Lille 4</nazwa>
                    <waga jednostka="kg">11,1</waga>
                    <cena waluta="zł">1549</cena>
                </rower>
                <rower Id="M03">
                    <producent idref="Le_Grand" />
                    <nazwa>Virginia 3</nazwa>
                    <waga jednostka="kg">9,8</waga>
                    <cena waluta="zł">2699</cena>
                </rower>
                <rower Id="M04">
                    <producent idref="Trek" />
                    <nazwa>T80 24 Speed Men</nazwa>
                    <waga jednostka="kg">10,8</waga>
                    <cena waluta="zł">3199</cena>
                </rower>
                <rower Id="M05">
                    <producent idref="Trek" />
                    <nazwa>X500 Stagger</nazwa>
                    <waga jednostka="kg">8,2</waga>
                    <cena waluta="zł">4499</cena>
                </rower>
            </lista_rowerów>
        </rodzaj> 
        <rodzaj Id="E">Elektryczne
            <opis>Typ rowerów z dodatkowym napędem elektrycznym wspomagającym pedałowanie</opis>
            <lista_rowerów>
                <rower Id="E01">
                    <producent idref="Kross" />
                    <nazwa>Lea Boost 1.0 </nazwa>
                    <waga jednostka="kg">11,8</waga>
                    <cena waluta="zł">9499</cena>
                </rower>
                <rower Id="E02">
                    <producent idref="Specialized" />
                    <nazwa>Turbo Levo FSR</nazwa>
                    <waga jednostka="kg">11,1</waga>
                    <cena waluta="zł">26899</cena>
                </rower>
                <rower Id="E03">
                    <producent idref="Trek" />
                    <nazwa>Powerfly 5</nazwa>
                    <waga jednostka="kg">12,1</waga>
                    <cena waluta="zł">13499</cena>
                </rower>
                <rower Id="E04">
                    <producent idref="Le_Grand" />
                    <nazwa>Elille 2</nazwa>
                    <waga jednostka="kg">9,9</waga>
                    <cena waluta="zł">4699</cena>
                </rower>
                <rower Id="E05">
                    <producent idref="Specialized" />
                    <nazwa>Turbo Vado 4.0 NB</nazwa>
                    <waga jednostka="kg">10,5</waga>
                    <cena waluta="zł">15699</cena>
                </rower>
            </lista_rowerów>
        </rodzaj>    
         <rodzaj Id="Z">Zjazdowy
            <opis>Typ rowerów przeznaczony do szybkich zjazdów po stromych zboczach</opis> 
            <lista_rowerów>
                <rower Id="Z01">
                    <producent idref="Specialized" />
                    <nazwa>Demo 8 Carbon</nazwa>
                    <waga jednostka="kg">8,2</waga>
                    <cena waluta="zł">26899</cena>
                </rower>
                <rower Id="Z02">
                    <producent idref="Specialized"/>
                    <nazwa>S-Works Demo 8</nazwa>
                    <waga jednostka="kg">9,2</waga>
                    <cena waluta="zł">40399</cena>
                </rower>
                <rower Id="Z03">
                    <producent idref="Specialized" />
                    <nazwa>Demo 8 Alloy</nazwa>
                    <waga jednostka="kg">8,8</waga>
                    <cena waluta="zł">18899</cena>
                </rower>
                <rower Id="Z04">
                    <producent idref="Trek" />
                    <nazwa>Session 8</nazwa>
                    <waga jednostka="kg">9,3</waga>
                    <cena waluta="zł">17999</cena>
                </rower>
                  <rower Id="Z05">
                    <producent idref="Trek" />
                    <nazwa>Session 9.9 DH 27.5</nazwa>
                    <waga jednostka="kg">10,2</waga>
                    <cena waluta="zł">37999</cena>
                </rower>
            </lista_rowerów>
        </rodzaj>
        <producenci>
            <p Id="Kross" kraj="Polska" />
           
            <p Id="Specialized" kraj="USA" />
           
             <p Id="Trek" kraj="USA" />
           
               <p Id="Le_Grand" kraj="Polska" />
           
        </producenci>   
    </sklep_rowerowy>  
</dokument>
