=== Bartosz-Banachowski/PKCK/Task3/skleprowerowy.xsd
<?xml version='1.0' encoding='UTF-8' ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:dok="http://www.example.org/dokument"
targetNamespace="http://www.example.org/dokument" 
elementFormDefault="qualified" >

<!--glowny dokument-->
<xsd:group name="DokumentGroup">
    <xsd:sequence> 
        <xsd:element name="autorzy" type="dok:KlasaAutor" /> 
        <xsd:element name="sklep_rowerowy" type="dok:KlasaSklep" /> 
    </xsd:sequence> 
</xsd:group>

<xsd:complexType name="KlasaDokument">
    <xsd:group ref="dok:DokumentGroup"/>
</xsd:complexType>

<!--autorzy-->
<xsd:complexType name="KlasaAutor">
    <xsd:sequence>
        <xsd:element name="autor" minOccurs="1" maxOccurs="unbounded" type="dok:KlasaDane"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="KlasaDane">
    <xsd:sequence>
        <xsd:element name="imię" type="dok:Imie"/>
        <xsd:element name="nazwisko" type="dok:Nazwisko"/>
        <xsd:element name="email" type="dok:Email"/>
    </xsd:sequence>
    <xsd:attribute name="Indeks" use="required" type="dok:KlasaIndeks"/>
</xsd:complexType>

<xsd:simpleType name="Imie"> 
    <xsd:restriction base="xsd:string">
        <xsd:minLength value="3"/>
        <xsd:maxLength value="40"/>
        <xsd:pattern value="([A-Z]{1}([a-z])*)" />
    </xsd:restriction> 
</xsd:simpleType>

<xsd:simpleType name="Nazwisko">
    <xsd:restriction base="xsd:string">
        <xsd:minLength value="3"/>
        <xsd:maxLength value="40"/>
        <xsd:pattern value="([A-Z]{1}([a-z])*)|([A-Z]{1}([a-z])*(\-|\s)([A-Z]{1}([a-z])*))" />
    </xsd:restriction> 
</xsd:simpleType>

<xsd:simpleType name="Email">
    <xsd:restriction base="xsd:string">
        <xsd:maxLength value="20"/>
        <xsd:pattern value="[0-9]{6}@edu.p.lodz.pl"/>
    </xsd:restriction> 
</xsd:simpleType>

<xsd:simpleType name="KlasaIndeks">
    <xsd:restriction base="xsd:positiveInteger">
        <xsd:pattern value="\d{6}"/>
    </xsd:restriction>
</xsd:simpleType>

<!--sklep rowerowy-->
<xsd:complexType name="KlasaSklep"> 
    <xsd:sequence> 
         <xsd:element name="rodzaj" minOccurs="1" maxOccurs="unbounded" type="dok:KlasaRodzaj" /> 
         <xsd:element name="producenci" type="dok:KlasaProducenci" />
         <xsd:element name="stopka" type="dok:KlasaStopka" />
    </xsd:sequence> 
</xsd:complexType>

<xsd:complexType name="KlasaRodzaj" mixed="true"> 
    <xsd:sequence> 
         <xsd:element name="opis" type="xsd:string" /> 
         <xsd:element name="lista_rowerów" type="dok:KlasaLista_Rowerow" /> 
    </xsd:sequence>
    <xsd:attribute name="Id" use="required" type="dok:IdRodzaj"/>
</xsd:complexType>   
        
 <xsd:complexType name="KlasaLista_Rowerow">
    <xsd:sequence>
        <xsd:element name="rower" minOccurs="0" maxOccurs="unbounded" type="dok:KlasaRower"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="KlasaRower">
    <xsd:sequence>
        <xsd:element name="producent" type="dok:KlasaProducent"/>
        <xsd:element name="nazwa" type="dok:KlasaNazwa"/>
        <xsd:element name="waga" type="dok:KlasaWaga"/>
        <xsd:element name="cena" type="dok:KlasaCena"/>
        <xsd:element name="RokZaprojektowania" type="dok:KlasaRokZaprojektowania"/>
    </xsd:sequence>
    <xsd:attribute name="Id" use="required" type="dok:IdRower"/>
 </xsd:complexType>   
 
 <xsd:complexType name="KlasaProducent">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute name="idref" use="required" type="dok:IdProducent"/>
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:simpleType name="KlasaNazwa">
    <xsd:restriction base="xsd:string">
        <xsd:maxLength value="64"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="KlasaWaga">
    <xsd:simpleContent>
        <xsd:extension base="xsd:double">
            <xsd:attribute name="jednostka" use="optional" type="dok:KlasaJednostki"/>
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:simpleType name="KlasaJednostki">
    <xsd:restriction base="xsd:token">
        <xsd:enumeration value="kg"/>
        <xsd:enumeration value="lbs"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="KlasaCena">
    <xsd:simpleContent>
        <xsd:extension base="xsd:double">
            <xsd:attribute name="waluta" use="required" type="dok:KlasaWaluta"/>
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>
 
<xsd:simpleType name="KlasaWaluta">
    <xsd:restriction base="xsd:token">
        <xsd:enumeration value="PLN"/>
        <xsd:enumeration value="EUR"/>
        <xsd:enumeration value="USD"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="KlasaRokZaprojektowania">
    <xsd:attribute name="rok" use="required" type="dok:KlasaRok"/>
</xsd:complexType>

<xsd:simpleType name="KlasaRok">
    <xsd:restriction base="xsd:gYear">
        <xsd:minInclusive value="1980" />
        <xsd:maxExclusive value="2020" />
    </xsd:restriction>
</xsd:simpleType>
        
<xsd:simpleType name="IdProducent"> 
    <xsd:restriction base="xsd:string">
        <xsd:maxLength value="20" />
        <xsd:pattern value="([A-Z]{1}([a-z])*)" />
    </xsd:restriction> 
</xsd:simpleType>

<xsd:simpleType name="IdRodzaj"> 
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="[A-Z]{1}" />
    </xsd:restriction> 
</xsd:simpleType>

<xsd:simpleType name="IdRower"> 
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="[A-Z]{1}[0-9][0-9]" />
    </xsd:restriction> 
</xsd:simpleType>

<xsd:complexType name="KlasaProducenci">
   <xsd:sequence>
        <xsd:element name="pochodzenie" maxOccurs="unbounded" type="dok:KlasaProducentRef"/>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="KlasaProducentRef">
   <xsd:attribute name="Id" use="required" type="dok:IdProducent"/>
   <xsd:attribute name="kraj" use="required" type="xsd:string"/>
</xsd:complexType> 

<xsd:element name="dokument" type="dok:KlasaDokument">
    <xsd:key name="IdKey">
        <xsd:selector xpath="dok:sklep_rowerowy/dok:producenci/dok:pochodzenie"/>
        <xsd:field xpath="@Id" />
    </xsd:key>
    <xsd:keyref name="LoginRef" refer="dok:IdKey">
        <xsd:selector xpath="dok:sklep_rowerowy/dok:rodzaj/dok:lista_rowerów/dok:rower/dok:producent"/>
        <xsd:field xpath="@idref" />
    </xsd:keyref>
</xsd:element>

<xsd:attributeGroup name="DatyDokumentuAttribute">
    <xsd:attribute name="dataUtworzenia" use="required" type="xsd:date"/>
    <xsd:attribute name="dataEdycji" use="required" type="xsd:date"/>
</xsd:attributeGroup>

<xsd:complexType name="KlasaStopka">
    <xsd:attributeGroup ref="dok:DatyDokumentuAttribute"/>
</xsd:complexType>

</xsd:schema>

=== Bartosz-Banachowski/PKCK/Task3/skleprowerowy.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="./skleprowerowy.css" type="text/css"?>

<dokument
xmlns="http://www.example.org/dokument"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/dokument skleprowerowy.xsd">

    <autorzy>
        <autor Indeks="203979">
            <imię>Lukasz</imię>
            <nazwisko>Rogozinski-Zlota</nazwisko>
            <email>203979@edu.p.lodz.pl</email>
        </autor>
        <autor Indeks="203849">
            <imię>Bartosz</imię>
            <nazwisko>Banachowski</nazwisko>
            <email>203849@edu.p.lodz.pl</email>
        </autor>
    </autorzy>

    <sklep_rowerowy>
        <rodzaj Id="S">Szosowy
            <opis>Typ rowerów przeznaczony do szybkiej jazdy po asfaltowej nawierzchni</opis> 
            <lista_rowerów>
                <rower Id="S01">
                    <producent idref="Kross" />
                    <nazwa>Kross Vento 2.0</nazwa>
                    <waga jednostka="kg">9.8</waga>
                    <cena waluta="EUR">2599</cena>
                    <RokZaprojektowania rok="2016"/>
                </rower>
                <rower Id="S02">
                    <producent idref="Specialized"/>
                    <nazwa>Allez Elite</nazwa>
                    <waga jednostka="kg">9.2</waga>
                    <cena waluta="USD">5799</cena>
                    <RokZaprojektowania rok="2017"/>
                </rower>
                <rower Id="S03">
                    <producent idref="Trek" />
                    <nazwa>Domane SL 6 Disc</nazwa>
                    <waga jednostka="kg">8.8</waga>
                    <cena waluta="PLN">15499</cena>
                    <RokZaprojektowania rok="2016"/>
                </rower>
                <rower Id="S04">
                    <producent idref="Kross" />
                    <nazwa>Vento Te</nazwa>
                    <waga jednostka="kg">7.1</waga>
                    <cena waluta="PLN">19999</cena>
                    <RokZaprojektowania rok="2018"/>
                </rower>
                  <rower Id="S05">
                    <producent idref="Trek" />
                    <nazwa>Madone 9.5</nazwa>
                    <waga jednostka="kg">8.0</waga>
                    <cena waluta="PLN">36999</cena>
                    <RokZaprojektowania rok="2016"/>
                </rower>
            </lista_rowerów>
        </rodzaj>
        <rodzaj Id="G">Górskie
            <opis>Typ rowerów przeznaczony do jazdy po cięzkim terenie</opis>
            <lista_rowerów>
                <rower Id="G01">
                    <producent idref="Kross" />
                    <nazwa>Level 14.0</nazwa>
                    <waga jednostka="kg">9.7</waga>
                    <cena waluta="PLN">15999</cena>
                    <RokZaprojektowania rok="2016"/>
                </rower>
                <rower Id="G02">
                    <producent idref="Specialized" />
                    <nazwa>S-Works XTR Di2</nazwa>
                    <waga jednostka="kg">8.3</waga>
                    <cena waluta="PLN">44999</cena>
                    <RokZaprojektowania rok="2017"/>
                </rower>
                <rower Id="G03">
                    <producent idref="Trek" />
                    <nazwa>Procaliber 9.7</nazwa>
                    <waga jednostka="kg">10.1</waga>
                    <cena waluta="PLN">11299</cena>
                    <RokZaprojektowania rok="2017"/>
                </rower>
                <rower Id="G04">
                    <producent idref="Kross" />
                    <nazwa>Roscoe 8</nazwa>
                    <waga jednostka="kg">8.8</waga>
                    <cena waluta="PLN">4899</cena>
                    <RokZaprojektowania rok="2018"/>
                </rower>
                <rower Id="G05">
                    <producent idref="Kross" />
                    <nazwa>Lea 4.0</nazwa>
                    <waga jednostka="kg">9.8</waga>
                    <cena waluta="PLN">1699</cena>
                    <RokZaprojektowania rok="2016"/>
                </rower>
            </lista_rowerów>
        </rodzaj>
		
        <rodzaj Id="M">Miejskie
            <opis>Typ rowerów przeznaczony do jazdy po mieście</opis>
            <lista_rowerów>
                <rower Id="M01">
                    <producent idref="Trek" />
                    <nazwa>T80 24 Speed Low</nazwa>
                    <waga jednostka="kg">10.2</waga>
                    <cena waluta="PLN">3199</cena>
                    <RokZaprojektowania rok="2018"/>
                </rower>
                <rower Id="M02">
                    <producent idref="Legrand" />
                    <nazwa>Lille 4</nazwa>
                    <waga jednostka="kg">11.1</waga>
                    <cena waluta="PLN">1549</cena>
                    <RokZaprojektowania rok="2018"/>
                </rower>
                <rower Id="M03">
                    <producent idref="Legrand" />
                    <nazwa>Virginia 3</nazwa>
                    <waga jednostka="kg">9.8</waga>
                    <cena waluta="PLN">2699</cena>
                    <RokZaprojektowania rok="2016"/>
                </rower>
                <rower Id="M04">
                    <producent idref="Trek" />
                    <nazwa>T80 24 Speed Men</nazwa>
                    <waga jednostka="kg">10.8</waga>
                    <cena waluta="PLN">3199</cena>
                    <RokZaprojektowania rok="2017"/>
                </rower>
                <rower Id="M05">
                    <producent idref="Trek" />
                    <nazwa>X500 Stagger</nazwa>
                    <waga jednostka="kg">8.2</waga>
                    <cena waluta="PLN">4499</cena>
                    <RokZaprojektowania rok="2018"/>
                </rower>
            </lista_rowerów>
        </rodzaj> 
		
        <rodzaj Id="E">Elektryczne
            <opis>Typ rowerów z dodatkowym napędem elektrycznym wspomagającym pedałowanie</opis>
            <lista_rowerów>
                <rower Id="E01">
                    <producent idref="Kross" />
                    <nazwa>Lea Boost 1.0 </nazwa>
                    <waga jednostka="kg">11.8</waga>
                    <cena waluta="PLN">9499</cena>
                    <RokZaprojektowania rok="2018"/>
                </rower>
                <rower Id="E02">
                    <producent idref="Specialized" />
                    <nazwa>Turbo Levo FSR</nazwa>
                    <waga jednostka="kg">11.1</waga>
                    <cena waluta="PLN">26899</cena>
                    <RokZaprojektowania rok="2018"/>
                </rower>
                <rower Id="E03">
                    <producent idref="Trek" />
                    <nazwa>Powerfly 5</nazwa>
                    <waga jednostka="kg">12.1</waga>
                    <cena waluta="PLN">13499</cena>
                    <RokZaprojektowania rok="2018"/>
                </rower>
                <rower Id="E04">
                    <producent idref="Legrand" />
                    <nazwa>Elille 2</nazwa>
                    <waga jednostka="kg">9.9</waga>
                    <cena waluta="PLN">4699</cena>
                    <RokZaprojektowania rok="2017"/>
                </rower>
                <rower Id="E05">
                    <producent idref="Specialized" />
                    <nazwa>Turbo Vado 4.0 NB</nazwa>
                    <waga jednostka="kg">10.5</waga>
                    <cena waluta="PLN">15699</cena>
                    <RokZaprojektowania rok="2018"/>
                </rower>
            </lista_rowerów>
        </rodzaj>    
		
         <rodzaj Id="Z">Zjazdowy
            <opis>Typ rowerów przeznaczony do szybkich zjazdów po stromych zboczach</opis> 
            <lista_rowerów>
                <rower Id="Z01">
                    <producent idref="Specialized" />
                    <nazwa>Demo 8 Carbon</nazwa>
                    <waga jednostka="kg">8.2</waga>
                    <cena waluta="PLN">26899</cena>
                    <RokZaprojektowania rok="2017"/>
                </rower>
                <rower Id="Z02">
                    <producent idref="Specialized"/>
                    <nazwa>S-Works Demo 8</nazwa>
                    <waga jednostka="kg">9.2</waga>
                    <cena waluta="PLN">40399</cena>
                    <RokZaprojektowania rok="2016"/>
                </rower>
                <rower Id="Z03">
                    <producent idref="Specialized" />
                    <nazwa>Demo 8 Alloy</nazwa>
                    <waga jednostka="kg">8.8</waga>
                    <cena waluta="PLN">18899</cena>
                    <RokZaprojektowania rok="2018"/>
                </rower>
                <rower Id="Z04">
                    <producent idref="Trek" />
                    <nazwa>Session 8</nazwa>
                    <waga jednostka="kg">9.3</waga>
                    <cena waluta="PLN">17999</cena>
                    <RokZaprojektowania rok="2016"/>
                </rower>
                  <rower Id="Z05">
                    <producent idref="Trek" />
                    <nazwa>Session 9.9 DH 27.5</nazwa>
                    <waga jednostka="kg">10.2</waga>
                    <cena waluta="PLN">37999</cena>
                    <RokZaprojektowania rok="2018"/>
                </rower>
            </lista_rowerów>
        </rodzaj>
		
        <producenci>
            <pochodzenie Id="Kross" kraj="Polska" />
            <pochodzenie Id="Specialized" kraj="USA" />
            <pochodzenie Id="Trek" kraj="USA" />
            <pochodzenie Id="Legrand" kraj="Polska" />           
        </producenci>   
		
        <stopka dataUtworzenia="2018-03-25" dataEdycji="2018-04-11" />
        
    </sklep_rowerowy>  
</dokument>
